const LOAD_TODOS_REQUEST = 'LOAD_TODOS_REQUEST';
const LOAD_TODOS_FAILURE = 'LOAD_TODOS_FAILURE';
const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';
const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
const REMOVE_TODO_FAILURE = 'REMOVE_TODO_FAILURE';
const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';

export default {
  LOAD_TODOS_REQUEST,
  LOAD_TODOS_FAILURE,
  LOAD_TODOS_SUCCESS,
  ADD_TODO_REQUEST,
  ADD_TODO_FAILURE,
  ADD_TODO_SUCCESS,
  REMOVE_TODO_REQUEST,
  REMOVE_TODO_FAILURE,
  REMOVE_TODO_SUCCESS
};
